[package]
name = "rusfuse"
version = "0.1.0"
authors = ["odd <odd12258053@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
libc = "0.2.81"
#signal-hook = "0.2.2"
